version: '3'

services:
  # - - - - - #
  hello_py:
    image: local/hello-python:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hello_python
    restart: "no"
    ports:
      - "5001:5001"
    env_file:
      - .env.example